faf-client:
  server:
    url: wss://lobby.faforever.xyz

  irc:
    host: irc.faforever.xyz
    port: 6697

  user:
    base-url: https://user.faforever.xyz

  vault:
    base-url: https://content.faforever.xyz
    replay-download-url-format: https://replay.faforever.xyz/%s

  news:
    feed-url: https://direct.faforever.xyz/news/feed

  website:
    base-url: https://www.faforever.xyz

  api:
    base-url: https://api.faforever.xyz

  oauth:
    base-url: https://hydra.faforever.xyz
    scopes: openid offline public_profile upload_map upload_mod lobby
    client-id: 2e8808cf-5889-469b-b2c3-01f0cc58c4af

  forged-alliance:
    exe-url: https://content.faforever.xyz/faf/updaterNew/updates_faf_files/ForgedAlliance.exe
