faf-client:
  server:
    url: wss://ws.faforever.com

  irc:
    host: irc.faforever.com
    port: 6697

  vault:
    base-url: https://content.faforever.com
    replay-download-url-format: https://replay.faforever.com/%s

  news:
    feed-url: https://direct.faforever.com/news/feed

  website:
    base-url: https://www.faforever.com

  api:
    base-url: https://api.faforever.com

  oauth:
    base-url: https://hydra.faforever.com
    scopes: openid offline public_profile upload_map upload_mod lobby
    client-id: 2e8808cf-5889-469b-b2c3-01f0cc58c4af

  forged-alliance:
    exe-url: https://content.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe

  use-remote-preferences: true
